language: node_js
node_js:
  - "6"
addons:
  chrome: stable
script:
  - npm run test:ci
before_install:
  - npm i -g @angular/cli
cache:
  directories:
    - "node_modules"
after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
